name: Build F.R.I.D.A.Y.

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      
    - name: Build F.R.I.D.A.Y. Release
      run: cargo build --release
      
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: FRIDAY-Windows-Build
        path: target/release/friday-rust-assistant.exe